# Generated by Django 5.1.4 on 2026-02-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
